### ISSUE TITLE
Anyone help for below program error-Grid Search Vs Random Search

### ISSUE THREAD

**Issue by SANGRAMSINHPATIL** [rritec/Machine-Learning#1]
Attached program of Grid Search Vs Random Search

[ML practice.zip](https://github.com/rritec/Machine-Learning/files/4487314/ML.practice.zip)

ref - https://www.kaggle.com/dkim1992/grid-search-vs-random-search.

**Comment by SANGRAMSINHPATIL** [comment]
param_grid = dict(svc_C = np.logspace(-2, 5, int(np.round(n_iter[i]**0.5))), svc_gamma = np.logspace(-5, 1, int(np.round(n_iter[i]**0.5))))

change this line of code

then it will work

np.round(n_iter[i]**0.5  as this statement producing float value, the base value is not allowing it, so we converted it into int. then it is working perfectly

**Comment by rritec** [comment]
closed
